name: Minecraft Server Status Checker

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Query Minecraft Server
        id: mc-status
        run: |
          SERVER_IP="nicely-kaufman.tun.ply.gg"
          RESPONSE=$(curl -s "https://mcsrvstat.us")
          ONLINE=$(echo "$RESPONSE" | jq '.online')
          
          if [ "$ONLINE" = "true" ]; then
            echo "STATUS=Online" >> $GITHUB_ENV
            echo "PLAYERS=$(echo "$RESPONSE" | jq '.players.online')/$(echo "$RESPONSE" | jq '.players.max')" >> $GITHUB_ENV
          else
            echo "STATUS=Offline" >> $GITHUB_ENV
            echo "PLAYERS=0/0" >> $GITHUB_ENV
          fi

      - name: Create Status Artifact
        run: |
          echo '{
            "endpoint": "dark-smp.github.io",
            "server_status": "${{ env.STATUS }}",
            "players_online": "${{ env.PLAYERS }}",
            "last_checked": "$(date -u)"
          }' > api.json

      - name: Upload Dynamic API File
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
